### ISSUE TITLE
NoMethodError: undefined method `sensitive' 

### ISSUE THREAD

**Issue by vesln** [phlipper/chef-postgresql#130]
Getting the following, when trying to setup users:

```
(postgresql::setup_users line 8) had an error: NoMethodError: undefined method `sensitive' for Chef::Resource::Execute
```

It's a wild guess but it seems like the Chef version I'm using doesn't support [sensitive](https://github.com/phlipper/chef-postgresql/blob/08718bbfc7461eb70dcddfdc2fc1c80b7c2767b2/providers/user.rb#L17). Upgrading, for me, will not be an option at this point. Any suggestions will be highly appreciated.

### Meta

Chef: 11.12.4
Cookbook version: git ref 08718bbfc7

**Comment by vesln** [comment]
Removing `sensitive` made it work. I will be using the fork until I get the chance to upgrade. Thank you

**Comment by phlipper** [comment]
@vesln thanks for the note. The `sensitive` attribute was introduced around Chef 11.13. Once you can update you should be fine.
