### ISSUE TITLE
Conditional enablement of service

### ISSUE THREAD

**Issue by vivid-inc** [phlipper/chef-postgresql#135]
Hi phlipper!

My Chef recipes **disable** the `postgresql` service (for valid reason), but the upstream `chef-postgresql::service` recipe **enables** the `postgresql` service unconditionally. The end result is the postgresql service flip-flops to enabled and then disabled again on each convergence run, manifesting into a kind of false-positive.

If possible, I'd like to be able to suppress the `action [:enable]` behavior via configuration on my side; a default of the current behavior is completely fine. If it helps, whether the postgresql daemon (service) is started or not is an unrelated matter. In short, my concern focuses on the `:enable` in `action [:enable, :start]`.

Thank you

**Comment by phlipper** [comment]
@vivid-inc I have a similar requirement in one of my infrastructures. In my case, I want to enable the service, but I don't want to start it until some additional recipes have been executed. You should be able to use something like the following to achieve what you are looking for:

```ruby
include_recipe "postgresql::server"

# don't enable the database server - override the action to just `start`
resources("service[postgresql]").action(:start)
```

I would also be willing to accept a PR which would make this configurable. Good luck!
