### ISSUE TITLE
Minified recipe

### ISSUE THREAD

**Issue by longtimeago** [phlipper/chef-postgresql#151]
Hi,
I'm a bit new to chef, so, possible, my question is stupid.
Is there any way to produce minified version of recipe to install postgre?
Or other way to reuse?

Thanks in advance!
Paul

**Comment by michaelklishin** [comment]
What do you mean by "minified"?

**Comment by longtimeago** [comment]
Well ... kindof "all in one" file to just copy ...

**Comment by michaelklishin** [comment]
Chef cookbooks can be distributed as tarballs and managed with [Berkshelf](http://berkshelf.com/), which can produce a tarball of all of your cookbooks. Then you can feed that tarball to `chef-solo`, for example.

However, Chef these days mostly assumes Chef server, so cookbooks are managed using Berkshelf and Knife (see Chef documentation).

**Comment by longtimeago** [comment]
@michaelklishin wow! Thank you for the hint! Will dig ...
